### ISSUE TITLE
Pass metadata from the auth webhook to the config server

### ISSUE THREAD

**Issue by patsys** [ContainerSSH/ContainerSSH#109]
## Please describe what you would like to see in ContainerSSH
Most Auth Server allow to return groups or roles to other applications(config server)

## Please describe the solution you'd like
The auth server output in the moment is only:
`{"success":"true"}`

I would like samething like this return value:
`{
   "success":"true",
   "groups":["group1","group2"]
}`

and then as input to the config server:
`{
  "username":"ssh username",
  "sessionId": "ssh session ID",
  "groups":["group1","group2"]
}`

## Please describe your use case
To manage more user I will map/merge the Configuration to Groups(Roles) and not to user, at the moment connect new to a auth server to a custom endpoint or manage user to groups in config server(wrong way).

**Comment by janoszen** [comment]
Hello @patsys,

I don't think we can pass groups this specifically since ContainerSSH is a generic implementation and groups seem to be specific to your use case and would not fit others.

What we could do is add a field called `metadata` where you can pass simple key-value pairs to the config server. However, this will take some significant changes to the internal architecture. In other words, this is not going to come in `0.4` since the release is almost complete. We can try and aim for `0.5` which will include significant improvements to the authentication system, but that's at least a few months out.

I know this is not ideal, but for the time being please work around this issue by fetching the groups from your data storage directly from the config server code.

**Comment by patsys** [comment]
Hello @janoszen 

That the `groups` field is too specific for my case only and a `metadata` field is useful I thought. I had also assumed that this is not done in `0.4`. It will be really interesting for me when the data come from another auth provider that sends the groups directly with the login.

**Comment by janoszen** [comment]
@patsys added it to the roadmap for 0.5, you'll see updates in this issue as it gets developed.

**Comment by janoszen** [comment]
This feature has a preliminary implementation in the [sshserver library version 2..0.0-alpha1](https://github.com/ContainerSSH/sshserver/releases/tag/v2.0.0-alpha.1). Implementation into the auth libraries coming soon.

**Comment by janosdebugs** [comment]
A little update after a username switch: the feature is currently well under way and here's a demonstration of a performed GitHub authentication and then the GitHub token being passed on to the container and used to query an avatar:

![image](https://user-images.githubusercontent.com/86970079/125000528-19c80600-e040-11eb-8fbf-d18fd6bfc004.png)

**Comment by tsipinakis** [comment]
Closing this, this is now supported with the new [authentication API](https://containerssh.io/upcoming/reference/api/authconfig/) coming in 0.5.
