### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by kfox1111** [ContainerSSH/ContainerSSH#137]
https://containerssh.io/getting-started/faq/#can-i-use-my-normal-kubeconfig-files

I think this can probably be done by using 'kubectl proxy' and pointing containerssh at the proxy.

**Comment by janoszen** [comment]
@kfox1111 not starting with 0.4 since we are removing support for contacting Kubernetes in "insecure" mode. We do not want to propagate using unencrypted connections.

Unfortunately, as far as we know the format of the kubeconfig is not documented and proprietary to kubectl. We have a partial implementation for integration tests, but in order to officially support it we would need the Kubernetes project to agree to not change the format at will.

**Is this a use case for you? If yes please rename this issue and we will add support for it with a warning.**

**Comment by kfox1111** [comment]
perhaps leaving insecure mode to work, but only with 127.0.0.1? kubectl proxy is still secure when used in that configuration.

No current use case. Just know it works well for the times I've needed complex auth with things that don't support it.

I can close the issue if you'd like.

**Comment by janoszen** [comment]
@kfox1111 thank you for your input, we really really appreciate it. Please don't take this as us being negative about your suggestion, quite the contrary.

127.0.0.1 is a good idea from a security perspective, however, from a human perspective I find it leads to bad things happening down the line. Some people treat their local network as secure, while others treat their leased fiber, MPLS, PPTP VPN, etc as secure. If we open the door an inch it will open the topic up for discussions for us to allow other IPs or IP ranges for insecure access too.

We'd much rather support kubeconfig with a warning if and when it becomes an issue for people. However, since ContainerSSH is intended to run in a container or on a server you would typically use it with a service account, not a kubeconfig file.

Main takeaway is that **if someone needs kubeconfig support they are welcome to request it and we'll patch it in.**
