### ISSUE TITLE
missing permission in entrypoint

### ISSUE THREAD

**Issue by sebastiansterk** [ContainerSSH/ContainerSSH#146]
## To Reproduce

If you can please provide the steps to reproduce the issue.

1. Clone containerssh git repo
2. Navigate to examples/quick-start
3. Follow the instructions
4. When performing docker-compose up -d the error occurs
--> 
```
Creating network "example_default" with the default driver
Creating example_authconfig_1   ... done
Creating example_containerssh_1 ... error

ERROR: for example_containerssh_1  Cannot start service containerssh: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/containerssh\": permission denied": unknown

ERROR: for containerssh  Cannot start service containerssh: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/containerssh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
```

## Expected behavior

containerssh container is getting created and is able to start

## Fix
inside the image, the "containerssh" file which is the entrypoint does not have execution permission. Fix: add a RUN command in dockerfile to set the permission: chmod +x containerssh

**Comment by janoszen** [comment]
Hello @sebastiansterk thank you very much, we have switched container build processes yesterday and this one slipped the net. We will fix it today and that should sole the problem.

**Comment by janoszen** [comment]
@sebastiansterk please accept my deepest apologies for this mishap, the issue has now been fixed. In order to get back on track please run the following two commands before `docker-compose up`:

```
docker pull containerssh/containerssh:0.3.1
docker-compose build
```

You don't need to do that in the future, it is only because of our build mistake that you now need to run this.

**Comment by sebastiansterk** [comment]
@janoszen please keep in mind that you are currently pushing new builds everytime to ALL image tags: https://hub.docker.com/r/containerssh/containerssh/tags
Yesterday I tried to switch back to older image tags which faced the same error. According to the update time they are getting updated always..

**Comment by janoszen** [comment]
@sebastiansterk this will not happen in the future. We are now adding a tag with the build date appended, so in the future you can switch back to the previous build. The format is `<containerssh version>-<container version>` This is necessary because the base image receives much more frequent security updates than we are releasing ContainerSSH versions.

Again, my apologies, we really messed this up, we should have, and will test better in the future.

**Comment by janoszen** [comment]
One more thing: if you need to reach out to us quickly in the future you can ping us on Discord: https://debugged.it/discord
