### ISSUE TITLE
Chroot feature

### ISSUE THREAD

**Issue by tomcsi** [ContainerSSH/ContainerSSH#240]
Hello,

I can setting up the containerssh, when the user connect to it, that user only use the one directory. Possible implementing this feature?

**Comment by janosdebugs** [comment]
This is already possible, but you need the program inside the container or on the backend SSH server to support it. Here's how:

- Using the [security restrictions](https://containerssh.io/reference/security/) you can restrict your user to only allow them in the SFTP subsystem, or alternatively force them to run everything through a program that chroots them.
- If you are not using a chrooting program, your SFTP server may support chrooting them.

Be sure to test all 3 scenarios:

- If the user tries to use SFTP.
- If the user tries to log in via console.
- If the user submits a command to run: `ssh user@yourserver "run-this-command"`.

All three should land the user in a chroot.

As for implementing it directly in ContainerSSH, yes, that would also be possible, but the binary that is executed must be located inside the chroot. That's why it is better to chroot after ContainerSSH has done its work.

I hope this helps. I'm closing this issue, feel free to reopen if this does not address your question.
