### ISSUE TITLE
User Selected Role Based SSH Configurations

### ISSUE THREAD

**Issue by GrantBirki** [ContainerSSH/ContainerSSH#595]
# User Selected Role Based SSH Configurations

Hey **containerssh** folks! 👋 

I have a question for you all:

If I have user bob and bob has two different job duties -> `database-operations` and `website-operations`

Is it possible to have a configuration server spawn a container of each type depending on what bob needs to do? For example, if bob needs to work on the database today, can he do something like `ssh foo@localhost --role=database` and that would provision a "database" specific container with things like mysql-client installed.

My goal is to give users the ability to use unique ssh roles so that what users want to do is scoped to least privilege. If bob doesn't need to do website operations work today, his container shouldn't contain any secrets or utilities to do so.

**Comment by tsipinakis** [comment]
(Reply adapted from a [thread](https://cloud-native.slack.com/archives/C0440TB5SP9/p1712078381315239) in the CNCF Slack)

Hey, great question, so in general the answer is no since as far as I know there is no way to pass arbitrary variables to ssh per-connection other than env-variables, which are an option, however env vars are sent very late in the ssh process, when requesting the shell channel). This may be possible to be supported in general with the [session mode](https://containerssh.io/upcoming/reference/docker/?h=mode#other-options) where every shell request is a new container - but this means with ControlMaster you get a new container per request - if that sounds interesting send a feature request, or even better a MR.

Though if you're using OIDC or Kerberos there is a cool hack: Use the username field, in oidc or Kerberos auth the username is quite redundant as it's taken from the oidc server for oidc and auth principal in the case of Kerberos. So bob can `ssh database@example.org` and with oidc or Kerberos and some authorization/config server magic you can make the end session end up as bob in the correct environment

In the [authorization](https://containerssh.io/v0.5/reference/auth-webhook/) and the [configuration](https://containerssh.io/upcoming/reference/configserver/#the-configuration-webhook) hooks you have two username fields - username is what the user provides in the command line e.g. -> database@example.com -> username = database 

Then there's `authenticatedUsername` If you authenticate via oidc as user bob then authenticatedUsername = bob

By default, as it should, this is rejected as bob is trying to log in as user database, no-go. However you can [set enforceUsernames to false](https://containerssh.io/v0.5/reference/auth-oauth2/#github-configuration) and this will allow any user to sign into any other user. You probably don't want this as a free-for-all though so you can top it off with an [authorization hook](https://containerssh.io/v0.5/reference/auth-webhook/#authorization) to check if 'bob' can log in as 'database'. Then in the config hook just make sure to use the authenticatedUsername as the user/uid
