### ISSUE TITLE
Kerberos/GSS-API authentication

### ISSUE THREAD

**Issue by ghost** [ContainerSSH/ContainerSSH#67]

**Comment by tsipinakis** [comment]
Hi, we're trialing a deployment ssh service and containerssh seems like a perfect fit. However, kerberos and PAM are critical functions that we can't do without

I'd be interested in working to implement this, and probably #64 (PAM) alongside. Would you accept a PR for this?

More importantly is the development of this project still ongoing?

**Comment by janosdebugs** [comment]
Hello @tsipinakis thank you very much for your interest in this project.

To answer your question, yes, we would accept a PR for this, and yes, the development of this project is still ongoing, but I have not been able to complete my current goal (oAuth). It is about 70% done, but my daily work took me away from it. I'm hoping to continue fairly soon.

As for your question about Kerberos and PAM, I did a little digging and here's what I found:

1. Kerberos / GSS-API is directly supported in the Go SSH library, so it shouldn't be too hard to get it implemented. However, this is tightly coupled with the SSH library itself, so it did not fit with the current pluggable architecture described in the [sshserver package](https://github.com/containerssh/sshserver). It would best be implemented by adding a config option to validate the Kerberos ticket. The new oAuth development also adds the ability to pass key-value configmaps from the authentication system to the configuration system, so you could use this to pass along information if needed.
2. As for PAM, that one is trickier because it's a *NIX-only system and requires linking to external libraries (libpam). This is a challenge because the current system builds a single binary for ContainerSSH without external dependencies (apart from libc). If we want to change that we need to make sure that the PAM-relevant parts are only built when the host OS is something PAM runs on. This can be done by putting the PAM-related parts in separate files with the proper build flags, as it is done in the [Docker backend, for example](https://github.com/ContainerSSH/docker/blob/main/config_connection_windows.go#L1). It may be better to do the PAM integration in an external configuration server if you only want to use this for starting a user session / etc.

I realize that ContainerSSH is not the easiest to contribute to, simply due to the sheer complexity. If you'd like we could set up a call and see how to get your use-case covered in the easiest way possible. If you're interested please contact me `handshake [at] containerssh.io`

**Comment by tsipinakis** [comment]
Doing some cleanup, closing this as kerberos support has already been implemented already for 0.5.
